name: app_flutter
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_map: ^6.0.1
  syncfusion_flutter_maps: ^24.2.4
  flutter_map_tappable_polyline: any
  flutter_map_marker_cluster: ^1.2.0
  geolocator: ^10.0.0
  http: ^1.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.3
  image_picker: ^1.0.7
  flutter_dotenv: ^5.1.0
  location: ^5.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon.png"

flutter:

  
  
  
  uses-material-design: true
  
  
assets:
  - assets/  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
