name: app_flutter
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_map: ^6.0.1
  syncfusion_flutter_maps: ^24.2.4
  flutter_map_tappable_polyline: any
  flutter_map_marker_cluster: ^1.2.0
  geolocator: ^10.0.0
  http: ^1.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter




flutter:

  
  
  
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
